builds:
  - id: "linux-build"
    goos:
      - linux
    goarch:
      - amd64
    binary: xraybuilder

archives:
  -
    id: linux-archive

    builds:
      - "linux-build"

    meta: true

    name_template: "{{ .ProjectName }}_{{ .Version }}"

    files:
      - configs/client.template.json
      - configs/server.template.json
