version: 2

builds:
  - id: "linux-build"
    goos:
      - linux
    goarch:
      - amd64
    binary: xray-builder

archives:
  -
    id: linux-archive

    builds:
      - "linux-build"

    name_template: "{{ .ProjectName }}_{{ .Version }}"

    wrap_in_directory: true

    files:
      - configs/client.template.json
      - configs/server.template.json
