archives:
  -
    id: linux-archive

    builds:
    - default

    meta: true

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    files:
      - configs/client.template.json
      - configs/server.template.json
