on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        version: latest
        binary_name: "xraybuilder"
        github_token: ${{ secrets.GO_RELEASE_GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
