on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean -f .goreleaser.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GO_RELEASE_GITHUB_TOKEN }}
